apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: staging-wp
  annotations:
    ## Untuk menaikan batas upload file
    nginx.org/client-max-body-size: "10m"
    ## Memaksa jalan di https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: st-wp.ahmadwizam.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: wordpress
          servicePort: 80

#  tls:
#  - hosts:
#      - st-wp.ahmadwizam.site 
#   secretName: wp-staging-tls
